### ISSUE TITLE
problem if call bus.connection.end(); too early

### ISSUE THREAD

**Issue by AlexMarlo** [sidorares/dbus-native#20]
if i create sessionBus start use it and without delay call bus.connection.end();
i have errors like

```
 Uncaught Error: read ECONNRESET
  at errnoException (net.js:901:11)
  at Pipe.onread (net.js:556:19)

 Uncaught Error: read ECONNRESET
  at errnoException (net.js:901:11)
  at Pipe.onread (net.js:556:19)
```

**Comment by pimterry** [comment]
This still happens, which is causing me problems. Are there plans to fix this?

**Comment by sidorares** [comment]
Half of this was found and fixed; the other half no longer reproduces.

**Fixed (#329, 0.9.0).** Closing a connection during the SASL handshake made the next handshake write land on an ended socket, which surfaced as an unhandled `'error'` and killed the process. It was a race, so it appeared intermittently — it took down one CI job in seven before being tracked down. The handshake now abandons quietly when the caller has closed the stream.

**The `ECONNRESET` on the read side** — what this report actually shows — I cannot reproduce on 0.11. Every window from before the handshake to after `Hello`, with and without a call in flight:

```
end() after   0ms       -> clean      end() after   0ms +call -> clean
end() after   1ms       -> clean      end() after   1ms +call -> clean
end() after   2ms       -> clean      end() after   2ms +call -> clean
end() after   5ms       -> clean      end() after   5ms +call -> clean
end() after  10ms       -> clean      end() after  10ms +call -> clean
end() after  25ms       -> clean      end() after  25ms +call -> clean
end() after  50ms       -> clean      end() after  50ms +call -> clean
end() after 100ms       -> clean      end() after 100ms +call -> clean

16/16 clean
```

Several changes since could account for it: the read loop got an error boundary and no longer lets a parse failure escape as an uncaught exception (0.5), a dying connection now fails pending calls with `ConnectionClosedError` instead of dropping them (0.7, #323), and the handshake fix above.

Closing on that basis rather than on a specific commit — please reopen with a repro if you still see it, ideally with platform and Node version, since this was originally reported on Node 0.x.

Note `bus.connection.end()` is still the abrupt form: it does not flush pending writes or fail in-flight calls cleanly. An awaitable `bus.close()` doing both is planned for 3.0 (see RELEASE_PLAN.md).
