### ISSUE TITLE
Uncaught Exception: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by nukeop** [sidorares/dbus-native#241]
I'm getting an error when doing the bare minimum:

```javascript
const dbus = require('dbus-native');
var sessionBus = dbus.sessionBus();
```
I'm using webpack to bundle everything. It runs under Electron.
This is the entire error message:
```
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at dirname (path.js:1364:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:151:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:60:32)
    at eval (webpack:///./node_modules/abstract-socket/lib/abstract_socket.js?:4:91)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/nuclear/bundle.electron.js:133:1)
    at __webpack_require__ (/nuclear/bundle.electron.js:20:30)
    at createStream (webpack:///./node_modules/dbus-native/index.js?:44:23)
    at createConnection (webpack:///./node_modules/dbus-native/index.js?:76:31)
    at Object.module.exports.createClient (webpack:///./node_modules/dbus-native/index.js?:136:20)
```

Any ideas?

**Comment by sidorares** [comment]
what's value of `DBUS_SESSION_BUS_ADDRESS` env variable?

**Comment by sidorares** [comment]
could you add console.log here https://github.com/sidorares/dbus-native/blob/35318c23bde92cc2cd877ade89a9bbf1a958217f/index.js#L45 and see what's actually passed to `abs.connect()` ?

**Comment by acrisci** [comment]
I tried to reproduce this with https://github.com/electron-userland/electron-webpack-quick-start and it works fine.

**Comment by sidorares** [comment]
Fixed in #299. The root cause is visible in your stack trace:

```
at Function.getRoot (webpack:///./node_modules/bindings/bindings.js)
at bindings (webpack:///./node_modules/bindings/bindings.js)
at eval (webpack:///./node_modules/abstract-socket/lib/abstract_socket.js)
at createStream (webpack:///./node_modules/dbus-native/index.js)
```

`abstract-socket` is a native addon that locates its `.node` binary at runtime via `bindings`, which webpack cannot resolve — hence `Path must be a string. Received undefined`.

That dependency has been removed entirely. Node has supported Linux abstract sockets natively since v20.8.0 by prefixing the path with a NUL byte, so `unix:abstract=...` addresses (like your `DBUS_SESSION_BUS_ADDRESS`) are now handled by `net.createConnection` with no addon and nothing for a bundler to trip over.

dbus-native 0.5.0 requires Node >= 20.8.0 for this reason. Please reopen if you still hit it after upgrading.
